// healthier_enhanced images
export { default as healthier_enhanced_1 } from "./Enhanced/healthiersg_detail1.png";
export { default as healthier_enhanced_2 } from "./Enhanced/healthiersg_detail2.png";
export { default as healthier_enhanced_3 } from "./Enhanced/healthiersg_detail3.png";
export { default as healthier_enhanced_4 } from "./Enhanced/healthiersg_detail4.png";
export { default as healthier_enhanced_5 } from "./Enhanced/healthiersg_detail5.png";
export { default as healthier_enhanced_6 } from "./Enhanced/healthiersg_detail6.png";
export { default as healthier_enhanced_7 } from "./Enhanced/healthiersg_detail7.png";
export { default as healthier_enhanced_8 } from "./Enhanced/healthiersg_detail8.png";
export { default as healthier_enhanced_9 } from "./Enhanced/healthiersg_detail9.png";
export { default as healthier_enhanced_10 } from "./Enhanced/healthiersg_detail10.png";
export { default as healthier_enhanced_11 } from "./Enhanced/healthiersg_detail11.png";
export { default as healthier_enhanced_12 } from "./Enhanced/healthiersg_detail12.png";
export { default as healthier_enhanced_13 } from "./Enhanced/healthiersg_detail13.png";
export { default as healthier_enhanced_14 } from "./Enhanced/healthiersg_detail14.png";
export { default as healthier_enhanced_15 } from "./Enhanced/healthiersg_detail15.png";
export { default as healthier_enhanced_16 } from "./Enhanced/healthiersg_detail16.png";
export { default as healthier_enhanced_17 } from "./Enhanced/healthiersg_detail17.png";
export { default as healthier_enhanced_18 } from "./Enhanced/healthiersg_detail18.png";
export { default as healthier_enhanced_19 } from "./Enhanced/healthiersg_detail19.png";
export { default as healthier_enhanced_20 } from "./Enhanced/healthiersg_detail20.png";
export { default as healthier_enhanced_21 } from "./Enhanced/healthiersg_detail21.png";
export { default as healthier_enhanced_22 } from "./Enhanced/healthiersg_detail22.png";

//  healthier_original images
export { default as healthier_original_1 } from "./Original/healthiersg_image1.png";
export { default as healthier_original_2 } from "./Original/healthiersg_image2.png";
export { default as healthier_original_3 } from "./Original/healthiersg_image3.png";
export { default as healthier_original_4 } from "./Original/healthiersg_image4.png";
export { default as healthier_original_5 } from "./Original/healthiersg_image5.png";
export { default as healthier_original_6 } from "./Original/healthiersg_image6.png";
export { default as healthier_original_7 } from "./Original/healthiersg_image7.png";
export { default as healthier_original_8 } from "./Original/healthiersg_image8.png";
export { default as healthier_original_9 } from "./Original/healthiersg_image9.png";
export { default as healthier_original_10 } from "./Original/healthiersg_image10.png";
export { default as healthier_original_11 } from "./Original/healthiersg_image11.png";
export { default as healthier_original_12 } from "./Original/healthiersg_image12.png";
export { default as healthier_original_13 } from "./Original/healthiersg_image13.png";
export { default as healthier_original_14 } from "./Original/healthiersg_image14.png";
export { default as healthier_original_15 } from "./Original/healthiersg_image15.png";
export { default as healthier_original_16 } from "./Original/healthiersg_image16.png";
export { default as healthier_original_17 } from "./Original/healthiersg_image17.png";
export { default as healthier_original_18 } from "./Original/healthiersg_image18.png";
export { default as healthier_original_19 } from "./Original/healthiersg_image19.png";
export { default as healthier_original_20 } from "./Original/healthiersg_image20.png";
export { default as healthier_original_21 } from "./Original/healthiersg_image21.png";
export { default as healthier_original_22 } from "./Original/healthiersg_image22.png";

//cpf enhanced images
export { default as cpf_enhanced_1 } from "./Enhanced/cpf_detail1.png";
export { default as cpf_enhanced_2 } from "./Enhanced/cpf_detail2.png";
export { default as cpf_enhanced_3 } from "./Enhanced/cpf_detail3.png";
export { default as cpf_enhanced_4 } from "./Enhanced/cpf_detail4.png";
export { default as cpf_enhanced_5 } from "./Enhanced/cpf_detail5.png";
export { default as cpf_enhanced_6 } from "./Enhanced/cpf_detail6.png";
export { default as cpf_enhanced_7 } from "./Enhanced/cpf_detail7.png";
export { default as cpf_enhanced_8 } from "./Enhanced/cpf_detail8.png";
export { default as cpf_enhanced_9 } from "./Enhanced/cpf_detail9.png";
export { default as cpf_enhanced_10 } from "./Enhanced/cpf_detail10.png";
export { default as cpf_enhanced_11 } from "./Enhanced/cpf_detail11.png";
export { default as cpf_enhanced_12 } from "./Enhanced/cpf_detail12.png";
export { default as cpf_enhanced_13 } from "./Enhanced/cpf_detail13.png";
export { default as cpf_enhanced_14 } from "./Enhanced/cpf_detail14.png";

//cpf original images
export { default as cpf_original_1 } from "./Original/cpf_image1.png";
export { default as cpf_original_2 } from "./Original/cpf_image2.png";
export { default as cpf_original_3 } from "./Original/cpf_image3.png";
export { default as cpf_original_4 } from "./Original/cpf_image4.png";
export { default as cpf_original_5 } from "./Original/cpf_image5.png";
export { default as cpf_original_6 } from "./Original/cpf_image6.png";
export { default as cpf_original_7 } from "./Original/cpf_image7.png";
export { default as cpf_original_8 } from "./Original/cpf_image8.png";
export { default as cpf_original_9 } from "./Original/cpf_image9.png";
export { default as cpf_original_10 } from "./Original/cpf_image10.png";
export { default as cpf_original_11 } from "./Original/cpf_image11.png";
export { default as cpf_original_12 } from "./Original/cpf_image12.png";
export { default as cpf_original_13 } from "./Original/cpf_image13.png";
export { default as cpf_original_14 } from "./Original/cpf_image14.png";
